name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request
  push:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:  

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: pacman_test
      
      - name: Install backend dependencies
        run: npm install
        
      - name: Install frontend dependencies
        run: npm install --prefix ./client

      - name: Sequelize migration
        run: npm run migration:test

      - name: Testing
        run: npm run test:client
